---
- hosts: local_node
  gather_facts: True
  roles:
    - role: devops.bootstrap.network
      vars:
        mac_address: "{{ ansible_facts['default_ipv4']['macaddress'] }}"


  tasks:
    - name: Reboot machine
      ansible.builtin.reboot:
      become: yes
