---
- hosts: task_node
  gather_facts: true
  roles:
    - role: devops.bootstrap.network
    - role: devops.bootstrap.cpu
    - role: devops.bootstrap.storage


  post_tasks:
    # We need this to apply grub parameters
    - name: Reboot machine
      ansible.builtin.reboot:
      become: true

    - name: Get CPU info
      ansible.builtin.shell: dmidecode -t processor
      register: cpuinfo
      become: true

    - name: Show CPU info
      debug:
        msg: "{{ cpuinfo.stdout }}"
